spring.application.name=SecondChance
spring.config.import=optional:classpath:application-secret.properties

google.maps.api.key=${GOOGLE_MAPS_API_KEY:default}
gemini.api.key=${GEMINI_API_KEY:default}
elevenlabs.api.key=${ELEVENLABS_API_KEY:default}

twilio.account.sid=${TWILIO_ACCOUNT_SID:default}
twilio.auth.token=${TWILIO_AUTH_TOKEN:default}
twilio.phone.from=${TWILIO_PHONE_NUMBER:default}
twilio.phone.to=${TWILIO_TO_PHONE_NUMBER:default}

# Used to expose local folders so audio files can be fetched via URL
spring.web.resources.static-locations=file:generated_audio/
